import { Inter } from "next/font/google";
import { ThemeProvider } from "@/components/home/theme-provider";
import type { Metadata } from "next";
import "./globals.css";
import ConvexClientProvider from "@/providers/convex-client-provider";
import {Toaster} from "react-hot-toast";


const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
      <ThemeProvider attribute='class' defaultTheme='system' enableSystem disableTransitionOnChange>
      <ConvexClientProvider>
        {children}
        <Toaster />
      </ConvexClientProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}

